### ISSUE TITLE
Some assets are not getting imported correctly

### ISSUE THREAD

**Issue by LawMixer** [NoTwistedHere/Figma-to-Roblox#4]
Hey, I can do this. I just started Figma today, and to be honest, this is a life changer. I do have one problem, when importing a UI. Some parts are invisible and not imported and will not show up. It's very annoying, any fix to this?

![](upload://dSjEShwVP5fI44snRiWJrQgXoWj.png)

**Comment by LawMixer** [comment]
https://i.imgur.com/RsHpQLt.png

**Comment by NoTwistedHere** [comment]
It's an issue to do with your design. Whatever comes first will come last when converting. Change the zIndex of whatever you can't see
